# Generated by Django 3.2.12 on 2022-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_keys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('api', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
    ]
