# Generated by Django 3.2.12 on 2022-03-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_keys',
            old_name='api_key',
            new_name='api_secret_key',
        ),
    ]
