# Generated by Django 3.2.12 on 2022-03-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_api_key_api_keys_api_secret_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_keys',
            old_name='api',
            new_name='api_key',
        ),
    ]
